# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-project:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: node:12
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
         - checkout
         - run: npm install
         - run: npm run eslint
         - run: npm run test
         - run: npm run build
         - run: git config --local user.name "ofirattia"
         - run: git config --local user.email "ofirattia@gmail.com"
         - run: git add .
         - run: git commit -m "update"
         - run: git push --set-upstream origin circleci-project-setup

workflows:
  build-project-workflow:
    jobs:
      - build-project
      - heroku/deploy-via-git:
          requires:
            - build-project
      
